module: mnist
model: MnistCNNClassifier


train:
    epochs: 50
    verbose: 1
    batch_size: 512
    validation_split: 0.1
    
    iteration: 3
    filters: [2, 4, 8]
    kernels: [3, 3, 3]

    compile:
        optimizer: adam
        loss: sparse_categorical_crossentropy
        metrics: [accuracy]
    
    checkpoint: 
        filepath: mnist_best.hdf5

    early_stopping:
        monitor: loss
        mode: min
    
    summary: true # default true
    tensorboard: true   # default false
        

test:
    checkpoint: mnist_best.hdf5